[profile.default]
bytecode_hash = "none"
evm_version = "cancun"
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
libs = ["lib"]
out = "out"
solc_version = "0.8.26"
src = "src"
via_ir = false

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
unichain_sepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"
unichain = "${UNICHAIN_RPC_URL}"

[etherscan]
unichain_sepolia = { key = "${UNISCAN_API_KEY}", chain = 1301, url = "https://api-sepolia.uniscan.xyz/api" }
unichain = { key = "${UNISCAN_API_KEY}", chain = 130, url = "https://api.uniscan.xyz/api" }
